//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otchi.Ebml.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otchi.Ebml.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to insert a child element that does not belong to the master.
        /// </summary>
        internal static string ChildOutOfRange {
            get {
                return ResourceManager.GetString("ChildOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has not been initialized..
        /// </summary>
        internal static string DocNotInitialized {
            get {
                return ResourceManager.GetString("DocNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file handler for the document that is to be parsed, has been closed or was never opened..
        /// </summary>
        internal static string FileClosed {
            get {
                return ResourceManager.GetString("FileClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open the file stream as it has been already opened before..
        /// </summary>
        internal static string FileStreamAlreadyOpen {
            get {
                return ResourceManager.GetString("FileStreamAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser state was invalid when an element tried to decode itself.
        /// </summary>
        internal static string InvalidDecodeState {
            get {
                return ResourceManager.GetString("InvalidDecodeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parsed document is not a valid EBML file. It is either missing the head or the body element..
        /// </summary>
        internal static string InvalidEbmlFile {
            get {
                return ResourceManager.GetString("InvalidEbmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parsed id was invalid and could not be read..
        /// </summary>
        internal static string InvalidIdValue {
            get {
                return ResourceManager.GetString("InvalidIdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A root element was not a master element. All root elements must be master elements..
        /// </summary>
        internal static string InvalidRootType {
            get {
                return ResourceManager.GetString("InvalidRootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical EBML Factory has not been registered. For the document to be parsed correctly, make sure at least the Root Elements are registered..
        /// </summary>
        internal static string MissingRootFactory {
            get {
                return ResourceManager.GetString("MissingRootFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No children left to parse..
        /// </summary>
        internal static string NoChildLeft {
            get {
                return ResourceManager.GetString("NoChildLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to add a child element for which the parent has not been parsed yet. .
        /// </summary>
        internal static string ParentNotParsed {
            get {
                return ResourceManager.GetString("ParentNotParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not override the specified Property.
        /// </summary>
        internal static string PropertyNotOverridable {
            get {
                return ResourceManager.GetString("PropertyNotOverridable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file was tried to be parsed. This is impossible.
        /// </summary>
        internal static string TriedToParseEmptyFile {
            get {
                return ResourceManager.GetString("TriedToParseEmptyFile", resourceCulture);
            }
        }
    }
}
